### PR TITLE
fix padding

### PR DESCRIPTION
**Pull request by trembon**
should fix https://github.com/giwty/switch-library-manager/issues/104

credits to: https://github.com/giwty/switch-library-manager/issues/104#issuecomment-1859295465

### CODE REVIEW

**Comment by firebat20** [comment]
I am currently using the lastest test build. I am still get the error. "failed to read NSP [reason: missing Key_area_key[key_area_key_application_0f]]". Let me know if there is any more information you need.

**Comment by firebat20** [comment]
Yes, I have the most recent prod with fw 17.0. I have attached a csv of a couple of the errors. I have more in another scan.

[errors.csv](https://github.com/trembon/switch-library-manager/files/14289830/errors.csv)

**Comment by trembon** [comment]
@firebat20 i'm only able to find one of these games as NSP and I have no problem processing those files. Could it be that you have had them processed from XCI to NSP and in that way made them unreadable?

**Comment by firebat20** [comment]
Thanks for looking into it. I have to check the source file, that might be the reason it is not working.

**Pull request merged**
